### ISSUE TITLE
不好意思啊，在这里提个问题

### ISSUE THREAD

**Issue by MrBoog** [zekunyan/HttpProxyExample#1]
继承于NSObject的都可用 runtime实现转发，可是为什么使用NSProxy？

**Comment by zekunyan** [comment]
@MrBoog 确实是这样=。=，但是NSProxy就是为了作为代理而设计的抽象类，子类要强制实现初始化和消息转发的相关方法，就是更加“专职”。当然，确实很多种方法都可以实现。

**Comment by zekunyan** [comment]
@MrBoog 不好意思回答晚了==

**Comment by MrBoog** [comment]
专职 +1
